import React from 'react';
import { Check, ChevronDown, ChevronRight, PanelLeft, PanelRight, X } from 'lucide-react';
import { ISO_INTERNAL_THREAD_CLASSES, ISO_METRIC_THREAD_SIZES, applyHoleStandard, findMetricThreadSize } from '../cad-core/hole-standards.js';
import { isDockableCommand } from './panel-layout.js';
import { Field } from './WorkspacePanels.jsx';

export function CommandDialog({ command, profileName, collapsed, dock, onChange, onConfirm, onConfirmDynamic, onCancel, onUndoSegment, onFinishPath, onToggleCollapsed, onToggleDock }) {
  if (!isDockableCommand(command)) return null;
  const isRectangle = command.type === 'rectangle';
  const isCircle = command.type === 'circle';
  const isArc = command.type === 'arc';
  const isPolygon = command.type === 'polygon';
  const isEllipse = command.type === 'ellipse';
  const isSlot = command.type === 'slot';
  const isSpline = command.type === 'spline';
  const isConic = command.type === 'conic';
  const isPoint = command.type === 'point';
  const isMechanicalShape = isRectangle || isCircle || isArc || isPolygon || isEllipse || isSlot || isSpline || isConic;
  const isExtrude = command.type === 'extrude';
  const isRevolve = command.type === 'revolve';
  const isSweep = command.type === 'sweep';
  const isLoft = command.type === 'loft';
  const isRib = command.type === 'rib';
  const isCoil = command.type === 'coil';
  const isPipe = command.type === 'pipe';
  const isPattern = command.type === 'pattern';
  const isBoolean = command.type === 'boolean';
  const isPrimitive = command.type === 'primitive';
  const isTransform = command.type === 'transform';
  const isOffsetFace = command.type === 'offsetFace';
  const isTextSolid = command.type === 'textSolid';
  const isHole = command.type === 'hole';
  const holeStandardApplication = command.holeApplication === 'clearance'
    ? `clearance-${command.clearanceClass || 'medium'}`
    : command.holeApplication === 'tapped' ? 'tapped' : 'custom';
  const selectedMetricSize = findMetricThreadSize(command.standardSize) || ISO_METRIC_THREAD_SIZES.find((size) => size.id === 'M6');
  const isFillet = command.type === 'fillet';
  const isShell = command.type === 'shell';
  const isDraftFeature = command.type === 'draft';
  const isSplitBody = command.type === 'splitBody';
  const isSplitFace = command.type === 'splitFace';
  const isDeleteFace = command.type === 'deleteFace';
  const isReplaceFace = command.type === 'replaceFace';
  const requiresFeaturePreview = isExtrude || isRevolve || isSweep || isLoft || isRib || isCoil || isPipe || isPattern || isBoolean || isPrimitive || isTransform || isOffsetFace || isTextSolid || isHole || isFillet || isShell || isDraftFeature || isSplitBody || isSplitFace || isDeleteFace || isReplaceFace;
  const featurePreviewPending = requiresFeaturePreview && !command.previewFeature;
  const isSketchPath = command.type === 'line' || command.type === 'polyline';
  const isSketchMove = command.type === 'moveSketch';
  const isSketchOffset = command.type === 'offsetSketch';
  const isSketchCorner = command.type === 'cornerSketch';
  const isSketchTransform = command.type === 'transformSketch';
  const isSketchPattern = command.type === 'patternSketch';
  const isOffsetPlane = command.type === 'offsetPlane';
  const isMidplane = command.type === 'midplanePlane';
  const isThreePointPlane = command.type === 'threePointPlane';
  const isAnglePlane = command.type === 'anglePlane';
  const isTangentPlane = command.type === 'tangentPlane';
  const isPathPlane = command.type === 'pathPlane';
  const isConstructionPlane = isOffsetPlane || isMidplane || isThreePointPlane || isAnglePlane || isTangentPlane || isPathPlane;
  const isConstructionAxis = command.type === 'constructionAxis';
  const axisTitles = { edge: 'Oś z krawędzi', cylinder: 'Oś walca', 'two-points': 'Oś przez dwa punkty', 'plane-intersection': 'Oś przecięcia płaszczyzn', 'plane-normal': 'Oś normalna do płaszczyzny' };
  const isConstructionPoint = command.type === 'constructionPoint';
  const pointTitles = { vertex: 'Punkt na wierzchołku', center: 'Punkt środka', intersection: 'Punkt przecięcia', midpoint: 'Punkt środkowy', 'on-axis': 'Punkt na osi' };
  const title = isRectangle ? 'Prostokąt' : isCircle ? 'Okrąg' : isArc ? 'Łuk' : isPolygon ? 'Wielokąt regularny' : isEllipse ? 'Elipsa' : isSlot ? 'Slot' : isSpline ? 'Spline' : isConic ? 'Krzywa conic' : isPoint ? 'Punkt szkicu' : isExtrude ? 'Wyciągnięcie' : isRevolve ? 'Revolve' : isSweep ? 'Sweep' : isLoft ? 'Loft' : isRib ? 'Rib/Web' : isCoil ? 'Coil' : isPipe ? 'Pipe' : isPattern ? 'Pattern' : isBoolean ? 'Boolean' : isPrimitive ? 'Prymityw 3D' : isTransform ? (command.mode === 'rotate' ? 'Obróć bryłę' : 'Przesuń bryłę') : isOffsetFace ? 'Offset Face' : isTextSolid ? 'Tekst 3D' : isHole ? 'Otwór' : isFillet ? 'Zaokrąglenie' : isShell ? 'Shell' : isDraftFeature ? 'Draft' : isSplitBody ? 'Split Body' : isSplitFace ? 'Split Face' : isDeleteFace ? 'Delete Face + Heal' : isReplaceFace ? 'Replace Face' : command.type === 'line' ? 'Linia' : command.type === 'polyline' ? 'Polilinia' : isSketchMove ? 'Przesuń geometrię' : isSketchOffset ? 'Offset szkicu' : isSketchCorner ? (command.mode === 'fillet' ? 'Fillet szkicu' : 'Chamfer szkicu') : isSketchTransform ? 'Transformuj szkic' : isSketchPattern ? 'Szyk szkicu' : isOffsetPlane ? 'Płaszczyzna odsunięta' : isMidplane ? 'Płaszczyzna środkowa' : isThreePointPlane ? 'Płaszczyzna przez trzy punkty' : isAnglePlane ? 'Płaszczyzna pod kątem' : isTangentPlane ? 'Płaszczyzna styczna' : isPathPlane ? 'Płaszczyzna na ścieżce' : isConstructionAxis ? axisTitles[command.axisType] : isConstructionPoint ? pointTitles[command.pointType] : 'Fazowanie';
  return (
    <section className={`command-dialog docked dock-${dock} ${collapsed ? 'collapsed' : ''} ${isSketchPath ? 'sketch-path-dialog' : ''}`} aria-label={`${title} — panel polecenia`}>
      <header>
        <strong>{title}</strong>
        <div className="dock-panel-actions">
          {!collapsed && <button type="button" data-panel-action="dock" onClick={onToggleDock} title={dock === 'right' ? 'Przenieś panel na lewą stronę' : 'Przenieś panel na prawą stronę'} aria-label={dock === 'right' ? 'Przenieś panel na lewą stronę' : 'Przenieś panel na prawą stronę'}>{dock === 'right' ? <PanelLeft size={15} /> : <PanelRight size={15} />}</button>}
          <button type="button" data-panel-action="collapse" onClick={onToggleCollapsed} title={collapsed ? 'Rozwiń panel polecenia' : 'Zwiń panel polecenia'} aria-label={collapsed ? 'Rozwiń panel polecenia' : 'Zwiń panel polecenia'} aria-expanded={!collapsed}>{collapsed ? <ChevronRight size={15} /> : <ChevronDown size={15} />}</button>
          {!collapsed && <button type="button" onClick={onCancel} title="Zamknij polecenie" aria-label="Zamknij polecenie"><X size={15} /></button>}
        </div>
      </header>
      {!collapsed && <>
      <div className="command-dialog-body">
        {isMechanicalShape && <Field label="Nazwa" value={command.name} onChange={(name) => onChange({ name })} />}
        {(isRectangle || isCircle || isArc || isPolygon || isEllipse || isSlot || isSpline) && (
          <label className="command-field">
            <span>Metoda</span>
            <select value={command.definition} onChange={(event) => onChange({ definition: event.target.value, gesturePoints: [] })} disabled={Boolean(command.editId)}>
              {isRectangle && <><option value="center">Środek i wymiary</option><option value="twoPoints">Dwa narożniki</option><option value="threePoints">Trzy punkty</option></>}
              {isCircle && <><option value="centerRadius">Środek i średnica</option><option value="twoPoints">Dwa punkty średnicy</option><option value="threePoints">Trzy punkty</option></>}
              {isArc && <><option value="threePoints">Trzy punkty</option><option value="centerStartEnd">Środek, początek, koniec</option></>}
              {isPolygon && <><option value="inscribed">Wpisany</option><option value="circumscribed">Opisany</option><option value="edge">Z krawędzi</option></>}
              {isEllipse && <><option value="full">Pełna elipsa</option><option value="arc">Łuk eliptyczny</option></>}
              {isSlot && <><option value="centerToCenter">Środek–środek</option><option value="overall">Długość całkowita</option><option value="threePoints">Trzy punkty</option><option value="arc">Po łuku</option></>}
              {isSpline && <><option value="fit">Punkty dopasowania</option><option value="control">Punkty kontrolne</option></>}
            </select>
          </label>
        )}
        {isRectangle && (
          <>
            {command.definition === 'center' ? <><Field label="Szerokość" value={command.width} onChange={(width) => onChange({ width })} suffix="mm" autoFocus /><Field label="Wysokość" value={command.height} onChange={(height) => onChange({ height })} suffix="mm" /><Field label="Środek X" value={command.x} onChange={(x) => onChange({ x })} suffix="mm" /><Field label="Środek Y" value={command.y} onChange={(y) => onChange({ y })} suffix="mm" /><Field label="Obrót" value={command.rotation} onChange={(rotation) => onChange({ rotation })} suffix="°" /></> : <><Field label="Punkt 1 X" value={command.x1} onChange={(x1) => onChange({ x1 })} suffix="mm" autoFocus /><Field label="Punkt 1 Y" value={command.y1} onChange={(y1) => onChange({ y1 })} suffix="mm" /><Field label="Punkt 2 X" value={command.x2} onChange={(x2) => onChange({ x2 })} suffix="mm" /><Field label="Punkt 2 Y" value={command.y2} onChange={(y2) => onChange({ y2 })} suffix="mm" />{command.definition === 'threePoints' && <><Field label="Punkt 3 X" value={command.x3} onChange={(x3) => onChange({ x3 })} suffix="mm" /><Field label="Punkt 3 Y" value={command.y3} onChange={(y3) => onChange({ y3 })} suffix="mm" /></>}</>}
          </>
        )}
        {isCircle && (
          <>
            {command.definition === 'centerRadius' ? <><Field label="Średnica" value={command.diameter} onChange={(diameter) => onChange({ diameter })} suffix="mm" autoFocus /><Field label="Środek X" value={command.x} onChange={(x) => onChange({ x })} suffix="mm" /><Field label="Środek Y" value={command.y} onChange={(y) => onChange({ y })} suffix="mm" /></> : <><Field label="Punkt 1 X" value={command.x1} onChange={(x1) => onChange({ x1 })} suffix="mm" autoFocus /><Field label="Punkt 1 Y" value={command.y1} onChange={(y1) => onChange({ y1 })} suffix="mm" /><Field label="Punkt 2 X" value={command.x2} onChange={(x2) => onChange({ x2 })} suffix="mm" /><Field label="Punkt 2 Y" value={command.y2} onChange={(y2) => onChange({ y2 })} suffix="mm" />{command.definition === 'threePoints' && <><Field label="Punkt 3 X" value={command.x3} onChange={(x3) => onChange({ x3 })} suffix="mm" /><Field label="Punkt 3 Y" value={command.y3} onChange={(y3) => onChange({ y3 })} suffix="mm" /></>}</>}
          </>
        )}
        {isArc && <><Field label={command.definition === 'centerStartEnd' ? 'Środek X' : 'Początek X'} value={command.x1} onChange={(x1) => onChange({ x1 })} suffix="mm" autoFocus /><Field label={command.definition === 'centerStartEnd' ? 'Środek Y' : 'Początek Y'} value={command.y1} onChange={(y1) => onChange({ y1 })} suffix="mm" /><Field label={command.definition === 'centerStartEnd' ? 'Początek X' : 'Punkt łuku X'} value={command.x2} onChange={(x2) => onChange({ x2 })} suffix="mm" /><Field label={command.definition === 'centerStartEnd' ? 'Początek Y' : 'Punkt łuku Y'} value={command.y2} onChange={(y2) => onChange({ y2 })} suffix="mm" /><Field label="Koniec X" value={command.x3} onChange={(x3) => onChange({ x3 })} suffix="mm" /><Field label="Koniec Y" value={command.y3} onChange={(y3) => onChange({ y3 })} suffix="mm" />{command.definition === 'centerStartEnd' && <label className="command-field"><span>Kierunek</span><select value={command.direction} onChange={(event) => onChange({ direction: event.target.value })}><option value="ccw">Przeciwnie do wskazówek</option><option value="cw">Zgodnie ze wskazówkami</option></select></label>}</>}
        {isPolygon && <>{command.definition === 'edge' ? <><Field label="Krawędź P1 X" value={command.x1} onChange={(x1) => onChange({ x1 })} suffix="mm" autoFocus /><Field label="Krawędź P1 Y" value={command.y1} onChange={(y1) => onChange({ y1 })} suffix="mm" /><Field label="Krawędź P2 X" value={command.x2} onChange={(x2) => onChange({ x2 })} suffix="mm" /><Field label="Krawędź P2 Y" value={command.y2} onChange={(y2) => onChange({ y2 })} suffix="mm" /></> : <><Field label="Promień" value={command.radius} onChange={(radius) => onChange({ radius })} suffix="mm" autoFocus /><Field label="Środek X" value={command.x} onChange={(x) => onChange({ x })} suffix="mm" /><Field label="Środek Y" value={command.y} onChange={(y) => onChange({ y })} suffix="mm" /><Field label="Obrót" value={command.rotation} onChange={(rotation) => onChange({ rotation })} suffix="°" /></>}<Field label="Liczba boków" value={command.sides} onChange={(sides) => onChange({ sides })} /></>}
        {isEllipse && <><Field label="Promień główny" value={command.majorRadius} onChange={(majorRadius) => onChange({ majorRadius })} suffix="mm" autoFocus /><Field label="Promień boczny" value={command.minorRadius} onChange={(minorRadius) => onChange({ minorRadius })} suffix="mm" /><Field label="Środek X" value={command.x} onChange={(x) => onChange({ x })} suffix="mm" /><Field label="Środek Y" value={command.y} onChange={(y) => onChange({ y })} suffix="mm" /><Field label="Obrót" value={command.rotation} onChange={(rotation) => onChange({ rotation })} suffix="°" />{command.definition === 'arc' && <><Field label="Kąt początku" value={command.startAngle} onChange={(startAngle) => onChange({ startAngle })} suffix="°" /><Field label="Kąt końca" value={command.endAngle} onChange={(endAngle) => onChange({ endAngle })} suffix="°" /><label className="command-field"><span>Kierunek</span><select value={command.direction} onChange={(event) => onChange({ direction: event.target.value })}><option value="ccw">Przeciwnie do wskazówek</option><option value="cw">Zgodnie ze wskazówkami</option></select></label></>}</>}
        {isSlot && <>{command.definition === 'arc' ? <><Field label="Środek X" value={command.x} onChange={(x) => onChange({ x })} suffix="mm" autoFocus /><Field label="Środek Y" value={command.y} onChange={(y) => onChange({ y })} suffix="mm" /><Field label="Promień osi" value={command.radius} onChange={(radius) => onChange({ radius })} suffix="mm" /><Field label="Kąt początku" value={command.startAngle} onChange={(startAngle) => onChange({ startAngle })} suffix="°" /><Field label="Kąt końca" value={command.endAngle} onChange={(endAngle) => onChange({ endAngle })} suffix="°" /><label className="command-field"><span>Kierunek</span><select value={command.direction} onChange={(event) => onChange({ direction: event.target.value })}><option value="ccw">Przeciwnie do wskazówek</option><option value="cw">Zgodnie ze wskazówkami</option></select></label></> : <><Field label="Punkt 1 X" value={command.x1} onChange={(x1) => onChange({ x1 })} suffix="mm" autoFocus /><Field label="Punkt 1 Y" value={command.y1} onChange={(y1) => onChange({ y1 })} suffix="mm" /><Field label="Punkt 2 X" value={command.x2} onChange={(x2) => onChange({ x2 })} suffix="mm" /><Field label="Punkt 2 Y" value={command.y2} onChange={(y2) => onChange({ y2 })} suffix="mm" />{command.definition === 'threePoints' && <><Field label="Punkt szerokości X" value={command.x3} onChange={(x3) => onChange({ x3 })} suffix="mm" /><Field label="Punkt szerokości Y" value={command.y3} onChange={(y3) => onChange({ y3 })} suffix="mm" /></>}</>}{command.definition !== 'threePoints' && <Field label="Szerokość" value={command.width} onChange={(width) => onChange({ width })} suffix="mm" />}</>}
        {isSpline && <Field label="Punkty X,Y" value={command.pointsText} onChange={(pointsText) => onChange({ pointsText })} autoFocus />}
        {isConic && <><Field label="Początek X" value={command.x1} onChange={(x1) => onChange({ x1 })} suffix="mm" autoFocus /><Field label="Początek Y" value={command.y1} onChange={(y1) => onChange({ y1 })} suffix="mm" /><Field label="Kontrola X" value={command.x2} onChange={(x2) => onChange({ x2 })} suffix="mm" /><Field label="Kontrola Y" value={command.y2} onChange={(y2) => onChange({ y2 })} suffix="mm" /><Field label="Koniec X" value={command.x3} onChange={(x3) => onChange({ x3 })} suffix="mm" /><Field label="Koniec Y" value={command.y3} onChange={(y3) => onChange({ y3 })} suffix="mm" /><Field label="Rho" value={command.rho} onChange={(rho) => onChange({ rho })} /><label className="command-field"><span>Ciągłość</span><select value={command.continuity} onChange={(event) => onChange({ continuity: event.target.value })}><option value="free">Swobodna (G0)</option><option value="tangent">Styczna (G1)</option><option value="curvature">Krzywizna (G2)</option></select></label></>}
        {isPoint && <><Field label="X" value={command.x} onChange={(x) => onChange({ x })} suffix="mm" autoFocus /><Field label="Y" value={command.y} onChange={(y) => onChange({ y })} suffix="mm" /><label className="command-field"><span>Rola</span><select value={command.role} onChange={(event) => onChange({ role: event.target.value })}><option value="standard">Referencja otworu</option><option value="construction">Konstrukcyjny</option></select></label></>}
        {(isExtrude || isRevolve || isSweep || isLoft || isRib || (isHole && command.placement !== 'face-edges')) && <Field label={isLoft ? 'Profil początkowy' : isRib ? 'Otwarty profil' : 'Profil'} value={profileName} disabled />}
        {isExtrude && (
          <>
            {!['through-all', 'to-object'].includes(command.extent) && <Field label={command.extent === 'symmetric' ? 'Długość całkowita' : 'Odległość'} value={command.distance} onChange={(distance) => onChange({ distance })} suffix="mm" autoFocus />}
            {command.extent === 'two-sides' && <Field label="Druga strona" value={command.secondDistance} onChange={(secondDistance) => onChange({ secondDistance })} suffix="mm" />}
            {command.extent === 'to-object' && <label className="command-field"><span>Obiekt docelowy</span><select value={command.targetReferenceId || ''} onChange={(event) => onChange({ targetReferenceId: event.target.value })}>{command.targetOptions.map((target) => <option key={target.id} value={target.id}>{target.name}</option>)}</select></label>}
            <Field label="Odsunięcie początku" value={command.startOffset} onChange={(startOffset) => onChange({ startOffset })} suffix="mm" />
            <label className="command-field"><span>Cienka ścianka</span><input type="checkbox" checked={Boolean(command.thin)} disabled={command.openChain} onChange={(event) => onChange({ thin: event.target.checked })} /></label>
            {command.thin && <><Field label="Grubość ścianki" value={command.wallThickness} onChange={(wallThickness) => onChange({ wallThickness })} suffix="mm" /><label className="command-field"><span>Strona ścianki</span><select value={command.wallSide} onChange={(event) => onChange({ wallSide: event.target.value })}><option value="inside">Do wewnątrz</option><option value="outside">Na zewnątrz</option><option value="symmetric">Symetrycznie</option></select></label>{command.openChain && <label className="command-field"><span>Zakończenie</span><select value={command.endCap} onChange={(event) => onChange({ endCap: event.target.value })}><option value="butt">Proste</option><option value="square">Wydłużone</option></select></label>}</>}
            <label className="command-field">
              <span>Operacja</span>
              <select value={command.operation} onChange={(event) => onChange({ operation: event.target.value })}>
                <option value="new">Nowa bryła</option>
                <option value="join">Połącz</option>
                <option value="cut">Wytnij</option>
                <option value="intersect">Część wspólna</option>
              </select>
            </label>
            <label className="command-field"><span>Kierunek</span><select value={command.extent} onChange={(event) => onChange({ extent: event.target.value })}><option value="one-side">Jedna strona</option><option value="two-sides">Dwie strony</option><option value="symmetric">Symetrycznie</option><option value="to-object" disabled={!command.targetOptions.length}>Do obiektu</option><option value="through-all" disabled={!['cut', 'intersect'].includes(command.operation)}>Through All</option></select></label>
          </>
        )}
        {isRevolve && <><label className="command-field"><span>Oś obrotu</span><select value={command.axisId} onChange={(event) => onChange({ axisId: event.target.value })}>{command.axisOptions.map((axis) => <option key={axis.id} value={axis.id}>{axis.name}</option>)}</select></label><Field label="Kąt Revolve" value={command.angle} onChange={(angle) => onChange({ angle })} suffix="°" autoFocus /><label className="command-field"><span>Operacja</span><select value={command.operation} onChange={(event) => onChange({ operation: event.target.value })}><option value="new">Nowa bryła</option><option value="join">Połącz</option><option value="cut">Wytnij</option><option value="intersect">Część wspólna</option></select></label></>}
        {isSweep && <><label className="command-field"><span>Ścieżka Sweep</span><select value={command.pathSketchId} onChange={(event) => onChange({ pathSketchId: event.target.value, pathEntityIds: command.pathOptions.find((path) => path.id === event.target.value)?.entityIds || [] })}>{command.pathOptions.map((path) => <option key={path.id} value={path.id}>{path.name}</option>)}</select></label><label className="command-field"><span>Operacja</span><select value={command.operation} onChange={(event) => onChange({ operation: event.target.value })}><option value="new">Nowa bryła</option><option value="join">Połącz</option><option value="cut">Wytnij</option><option value="intersect">Część wspólna</option></select></label></>}
        {isLoft && <><label className="command-field"><span>Profil końcowy</span><select value={command.endProfileId} onChange={(event) => { const target = command.profileOptions.find((profile) => profile.id === event.target.value); onChange({ endProfileId: target?.id || '', endSketchId: target?.sketchId || '' }); }}>{command.profileOptions.map((profile) => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label><label className="command-field"><span>Przejście</span><select value={command.loftMode} onChange={(event) => onChange({ loftMode: event.target.value })}><option value="smooth">Gładkie</option><option value="ruled">Odcinkowe</option></select></label><label className="command-field"><span>Operacja</span><select value={command.operation} onChange={(event) => onChange({ operation: event.target.value })}><option value="new">Nowa bryła</option><option value="join">Połącz</option><option value="cut">Wytnij</option><option value="intersect">Część wspólna</option></select></label></>}
        {isRib && <><label className="command-field"><span>Typ</span><select value={command.ribMode} onChange={(event) => onChange({ ribMode: event.target.value })}><option value="rib">Rib · wzrost w płaszczyźnie</option><option value="web">Web · wzrost prostopadły</option></select></label><Field label="Grubość" value={command.thickness} onChange={(thickness) => onChange({ thickness })} suffix="mm" autoFocus /><Field label="Zasięg" value={command.depth} onChange={(depth) => onChange({ depth })} suffix="mm" /><label className="command-field"><span>Strona</span><select value={command.wallSide} onChange={(event) => onChange({ wallSide: event.target.value })}><option value="inside">Lewa</option><option value="outside">Prawa</option><option value="symmetric">Symetrycznie</option></select></label><label className="command-field"><span>Odwróć kierunek</span><input type="checkbox" checked={Boolean(command.reverse)} onChange={(event) => onChange({ reverse: event.target.checked })} /></label></>}
        {isCoil && <><label className="command-field"><span>Oś Coil</span><select value={command.axisId} onChange={(event) => onChange({ axisId: event.target.value })}>{command.axisOptions.map((axis) => <option key={axis.id} value={axis.id}>{axis.name}</option>)}</select></label><Field label="Średnica Coil" value={command.coilDiameter} onChange={(coilDiameter) => onChange({ coilDiameter })} suffix="mm" autoFocus /><Field label="Średnica przekroju" value={command.wireDiameter} onChange={(wireDiameter) => onChange({ wireDiameter })} suffix="mm" /><Field label="Skok" value={command.pitch} onChange={(pitch) => onChange({ pitch })} suffix="mm" /><Field label="Liczba zwojów" value={command.turns} onChange={(turns) => onChange({ turns })} /><label className="command-field"><span>Kierunek zwoju</span><select value={command.handedness} onChange={(event) => onChange({ handedness: event.target.value })}><option value="right">Prawoskrętny</option><option value="left">Lewoskrętny</option></select></label><label className="command-field"><span>Operacja</span><select value={command.operation} onChange={(event) => onChange({ operation: event.target.value })}><option value="new">Nowa bryła</option><option value="join">Połącz</option><option value="cut">Wytnij</option><option value="intersect">Część wspólna</option></select></label></>}
        {isPipe && <><Field label="Ścieżka Pipe" value={profileName} disabled /><Field label="Średnica zewnętrzna" value={command.outsideDiameter} onChange={(outsideDiameter) => onChange({ outsideDiameter })} suffix="mm" autoFocus /><Field label="Grubość ścianki" value={command.wallThickness} onChange={(wallThickness) => onChange({ wallThickness })} suffix="mm" /><label className="command-field"><span>Operacja</span><select value={command.operation} onChange={(event) => onChange({ operation: event.target.value })}><option value="new">Nowa bryła</option><option value="join">Połącz</option><option value="cut">Wytnij</option><option value="intersect">Część wspólna</option></select></label></>}
        {isPattern && <><Field label="Bryła źródłowa" value={command.targetBodyId} disabled /><label className="command-field"><span>Typ szyku</span><select value={command.patternType} onChange={(event) => onChange({ patternType: event.target.value })}><option value="rectangular">Prostokątny</option><option value="circular">Kołowy</option><option value="path" disabled={!command.pathOptions.length}>Po ścieżce</option></select></label>{command.patternType === 'rectangular' && <><Field label="Kolumny" value={command.countX} onChange={(countX) => onChange({ countX })} /><Field label="Wiersze" value={command.countY} onChange={(countY) => onChange({ countY })} /><Field label="Odstęp X" value={command.spacingX} onChange={(spacingX) => onChange({ spacingX })} suffix="mm" /><Field label="Odstęp Y" value={command.spacingY} onChange={(spacingY) => onChange({ spacingY })} suffix="mm" /></>}{command.patternType === 'circular' && <><label className="command-field"><span>Oś szyku</span><select value={command.axisId} onChange={(event) => onChange({ axisId: event.target.value })}>{command.axisOptions.map((axis) => <option key={axis.id} value={axis.id}>{axis.name}</option>)}</select></label><Field label="Wystąpienia" value={command.occurrences} onChange={(occurrences) => onChange({ occurrences })} /><Field label="Kąt całkowity" value={command.totalAngle} onChange={(totalAngle) => onChange({ totalAngle })} suffix="°" /></>}{command.patternType === 'path' && <><label className="command-field"><span>Ścieżka</span><select value={command.pathSketchId} onChange={(event) => { const path = command.pathOptions.find((item) => item.id === event.target.value); onChange({ pathSketchId: path?.id, pathEntityIds: path?.entityIds || [] }); }}>{command.pathOptions.map((path) => <option key={path.id} value={path.id}>{path.name}</option>)}</select></label><Field label="Wystąpienia" value={command.occurrences} onChange={(occurrences) => onChange({ occurrences })} /></>}</>}
        {isBoolean && (
          <>
            <Field label="Bryła bazowa" value={command.targetName || command.targetBodyId} disabled />
            <Field label="Bryła narzędziowa" value={command.toolName || command.toolBodyId} disabled />
            <label className="command-field"><span>Operacja</span><select value={command.operation} onChange={(event) => onChange({ operation: event.target.value })}><option value="union">Union</option><option value="subtract">Subtract</option><option value="intersect">Intersect</option></select></label>
          </>
        )}
        {isPrimitive && (
          <>
            <Field label="Nazwa" value={command.name} onChange={(name) => onChange({ name })} />
            <label className="command-field"><span>Typ</span><select value={command.primitiveType} onChange={(event) => onChange({ primitiveType: event.target.value })}><option value="box">Box</option><option value="cylinder">Cylinder</option><option value="sphere">Sphere</option><option value="torus">Torus</option></select></label>
            {command.primitiveType === 'box' && <><Field label="Szerokość" value={command.width} onChange={(width) => onChange({ width })} suffix="mm" autoFocus /><Field label="Głębokość" value={command.depth} onChange={(depth) => onChange({ depth })} suffix="mm" /><Field label="Wysokość" value={command.height} onChange={(height) => onChange({ height })} suffix="mm" /></>}
            {command.primitiveType === 'cylinder' && <><Field label="Promień" value={command.radius} onChange={(radius) => onChange({ radius })} suffix="mm" autoFocus /><Field label="Wysokość" value={command.height} onChange={(height) => onChange({ height })} suffix="mm" /></>}
            {command.primitiveType === 'sphere' && <Field label="Promień" value={command.radius} onChange={(radius) => onChange({ radius })} suffix="mm" autoFocus />}
            {command.primitiveType === 'torus' && <><Field label="Promień główny" value={command.majorRadius} onChange={(majorRadius) => onChange({ majorRadius })} suffix="mm" autoFocus /><Field label="Promień przekroju" value={command.minorRadius} onChange={(minorRadius) => onChange({ minorRadius })} suffix="mm" /></>}
            <Field label="Położenie X" value={command.x} onChange={(x) => onChange({ x })} suffix="mm" />
            <Field label="Położenie Y" value={command.y} onChange={(y) => onChange({ y })} suffix="mm" />
            <Field label="Położenie Z" value={command.z} onChange={(z) => onChange({ z })} suffix="mm" />
          </>
        )}
        {isTransform && (command.mode === 'move' ? <><Field label="Przesunięcie X" value={command.x} onChange={(x) => onChange({ x })} suffix="mm" autoFocus /><Field label="Przesunięcie Y" value={command.y} onChange={(y) => onChange({ y })} suffix="mm" /><Field label="Przesunięcie Z" value={command.z} onChange={(z) => onChange({ z })} suffix="mm" /></> : <><Field label="Kąt Z" value={command.angle} onChange={(angle) => onChange({ angle })} suffix="°" autoFocus /><Field label="Środek X" value={command.originX} onChange={(originX) => onChange({ originX })} suffix="mm" /><Field label="Środek Y" value={command.originY} onChange={(originY) => onChange({ originY })} suffix="mm" /><Field label="Środek Z" value={command.originZ} onChange={(originZ) => onChange({ originZ })} suffix="mm" /></>)}
        {isOffsetFace && <><Field label="Ściana" value={command.faceLabel || '1 wskazana'} disabled /><Field label="Odległość" value={command.distance} onChange={(distance) => onChange({ distance })} suffix="mm" autoFocus /></>}
        {isTextSolid && <><Field label="Tekst" value={command.text} onChange={(text) => onChange({ text })} autoFocus /><Field label="Rozmiar" value={command.fontSize} onChange={(fontSize) => onChange({ fontSize })} suffix="mm" /><Field label="Głębokość" value={command.depth} onChange={(depth) => onChange({ depth })} suffix="mm" /><label className="command-field"><span>Operacja</span><select value={command.operation} onChange={(event) => onChange({ operation: event.target.value })}><option value="new">Nowa bryła</option><option value="emboss" disabled={!command.targetBodyId}>Emboss — wypukły</option><option value="deboss" disabled={!command.targetBodyId}>Deboss — wklęsły</option></select></label>{command.placement === 'face' && <Field label="Powierzchnia" value="Planarna ściana (trwała referencja)" disabled />}<Field label="Położenie X" value={command.x} onChange={(x) => onChange({ x })} suffix="mm" /><Field label="Położenie Y" value={command.y} onChange={(y) => onChange({ y })} suffix="mm" />{command.placement !== 'face' && <Field label={command.operation === 'new' ? 'Położenie Z' : 'Powierzchnia Z'} value={command.z} onChange={(z) => onChange({ z })} suffix="mm" />}</>}
        {isHole && (
          <>
            {command.placement === 'face-edges' && <><Field label="Pozycjonowanie" value="Ściana + 2 krawędzie" disabled /><Field label="Od krawędzi 1" value={command.firstOffset} onChange={(firstOffset) => onChange({ firstOffset })} suffix="mm" autoFocus /><Field label="Od krawędzi 2" value={command.secondOffset} onChange={(secondOffset) => onChange({ secondOffset })} suffix="mm" /></>}
            <label className="command-field"><span>Zastosowanie</span><select value={holeStandardApplication} onChange={(event) => onChange(applyHoleStandard(command, event.target.value, command.standardSize || 'M6'))}><option value="custom">Własne wymiary</option><option value="clearance-fine">ISO 273 — przejściowy bliski</option><option value="clearance-medium">ISO 273 — przejściowy normalny</option><option value="clearance-coarse">ISO 273 — przejściowy duży</option><option value="tapped">ISO metryczny — gwintowany</option></select></label>
            {holeStandardApplication !== 'custom' && <label className="command-field"><span>Rozmiar śruby / gwintu</span><select value={selectedMetricSize.id} onChange={(event) => onChange(applyHoleStandard(command, holeStandardApplication, event.target.value))}>{ISO_METRIC_THREAD_SIZES.map((size) => <option key={size.id} value={size.id}>{size.id}</option>)}</select></label>}
            <label className="command-field"><span>Typ otworu</span><select value={command.holeType} onChange={(event) => onChange({ holeType: event.target.value })}><option value="simple">Prosty</option><option value="counterbore">Counterbore</option><option value="countersink">Countersink</option></select></label>
            <Field label={holeStandardApplication === 'tapped' ? 'Średnica wiertła' : 'Średnica'} value={command.diameter} onChange={(diameter) => onChange({ diameter })} suffix="mm" disabled={holeStandardApplication !== 'custom'} autoFocus />
            <label className="command-field"><span>Zakres</span><select value={command.extent} onChange={(event) => onChange({ extent: event.target.value })}><option value="distance">Na odległość</option><option value="through-all">Przez wszystko</option></select></label>
            {command.extent === 'distance' && <Field label="Głębokość" value={command.depth} onChange={(depth) => onChange({ depth })} suffix="mm" />}
            {command.holeType === 'counterbore' && <><Field label="Średnica Counterbore" value={command.counterboreDiameter} onChange={(counterboreDiameter) => onChange({ counterboreDiameter })} suffix="mm" /><Field label="Głębokość Counterbore" value={command.counterboreDepth} onChange={(counterboreDepth) => onChange({ counterboreDepth })} suffix="mm" /></>}
            {command.holeType === 'countersink' && <><Field label="Średnica Countersink" value={command.countersinkDiameter} onChange={(countersinkDiameter) => onChange({ countersinkDiameter })} suffix="mm" /><Field label="Kąt Countersink" value={command.countersinkAngle} onChange={(countersinkAngle) => onChange({ countersinkAngle })} suffix="°" /></>}
            {command.holeApplication !== 'clearance' && <label className="command-field"><span>Gwint</span><select value={command.threadMode} onChange={(event) => onChange({ threadMode: event.target.value })}><option value="none" disabled={holeStandardApplication === 'tapped'}>Brak</option><option value="cosmetic">Kosmetyczny</option><option value="modeled">Modelowany</option></select></label>}
            {command.threadMode !== 'none' && command.holeApplication !== 'clearance' && <><Field label="Średnica gwintu" value={command.threadDiameter} onChange={(threadDiameter) => onChange({ threadDiameter })} suffix="mm" disabled={holeStandardApplication === 'tapped'} />{holeStandardApplication === 'tapped' ? <label className="command-field"><span>Skok gwintu</span><select value={String(command.threadPitch)} onChange={(event) => onChange(applyHoleStandard(command, 'tapped', selectedMetricSize.id, event.target.value))}>{selectedMetricSize.pitches.map((pitch) => <option key={pitch} value={pitch}>{pitch} mm</option>)}</select></label> : <Field label="Skok gwintu" value={command.threadPitch} onChange={(threadPitch) => onChange({ threadPitch })} suffix="mm" />}<Field label="Długość gwintu" value={command.threadLength} onChange={(threadLength) => onChange({ threadLength })} suffix="mm" /><label className="command-field"><span>Kierunek gwintu</span><select value={command.threadDirection} onChange={(event) => onChange({ threadDirection: event.target.value })}><option value="right">Prawy</option><option value="left">Lewy</option></select></label>{holeStandardApplication === 'tapped' && <label className="command-field"><span>Klasa gwintu</span><select value={command.threadClass || '6H'} onChange={(event) => onChange({ threadClass: event.target.value })}>{ISO_INTERNAL_THREAD_CLASSES.map((threadClass) => <option key={threadClass} value={threadClass}>{threadClass}</option>)}</select></label>}</>}
            {holeStandardApplication === 'custom' && <label className="command-field"><span>Profil luzu</span><select value={command.clearanceProfile} onChange={(event) => onChange({ clearanceProfile: event.target.value })}><option value="nominal">Nominalny</option><option value="fff">FFF</option></select></label>}
            {holeStandardApplication === 'custom' && command.clearanceProfile === 'fff' && <Field label="Luz promieniowy FFF" value={command.clearance} onChange={(clearance) => onChange({ clearance })} suffix="mm" />}
          </>
        )}
        {(isFillet || command.type === 'chamfer') && (
          <Field label={isFillet ? 'Promień' : 'Odległość'} value={command.size} onChange={(size) => onChange({ size })} suffix="mm" autoFocus />
        )}
        {isShell && <><Field label="Usuwane ściany" value={`${command.faceCount || 0}`} disabled /><Field label="Grubość" value={command.thickness} onChange={(thickness) => onChange({ thickness })} suffix="mm" autoFocus /></>}
        {isDraftFeature && <><Field label="Pochylane ściany" value={`${command.faceCount || 0}`} disabled /><label className="command-field"><span>Płaszczyzna neutralna</span><select value={command.neutralPlaneId} onChange={(event) => onChange({ neutralPlaneId: event.target.value })}>{command.neutralPlaneOptions.map((plane) => <option key={plane.id} value={plane.id}>{plane.name}</option>)}</select></label><Field label="Kąt Draft" value={command.angle} onChange={(angle) => onChange({ angle })} suffix="°" autoFocus /></>}
        {isSplitBody && <><Field label="Bryła dzielona" value={command.targetName || command.targetBodyId} disabled /><label className="command-field"><span>Płaszczyzna podziału</span><select value={command.planeId} onChange={(event) => onChange({ planeId: event.target.value })}>{command.planeOptions.map((plane) => <option key={plane.id} value={plane.id}>{plane.name}</option>)}</select></label></>}
        {isSplitFace && <><Field label="Profil podziału" value={command.profileName || command.profileId} disabled /><Field label="Ściana dzielona" value={command.faceName || 'Planarna ściana szkicu'} disabled /></>}
        {isDeleteFace && <><Field label="Usuwane regiony" value={`${command.faceCount || 0}`} disabled /><p className="command-hint">Operacja scala wskazane regiony z sąsiednimi ścianami leżącymi na tej samej powierzchni.</p></>}
        {isReplaceFace && <><Field label="Ściana zastępowana" value={command.sourceName || 'Pierwsza zaznaczona ściana'} disabled /><Field label="Powierzchnia docelowa" value={command.destinationName || 'Druga zaznaczona ściana'} disabled /><p className="command-hint">Planarne i równoległe ściany mogą należeć do dwóch różnych brył; bryła powierzchni docelowej pozostaje bez zmian.</p></>}
        {isConstructionPlane && (
          <>
            <Field label="Nazwa" value={command.name} onChange={(name) => onChange({ name })} autoFocus />
            {(isOffsetPlane || isMidplane || isAnglePlane) && <label className="command-field"><span>Płaszczyzna bazowa</span><select value={command.basePlane} onChange={(event) => onChange({ basePlane: event.target.value })}><option value="XY">Góra (XY)</option><option value="XZ">Przód (XZ)</option><option value="YZ">Prawo (YZ)</option></select></label>}
            {isOffsetPlane && <Field label="Odległość" value={command.offset} onChange={(offset) => onChange({ offset })} suffix="mm" />}
            {isMidplane && <><Field label="Położenie A" value={command.firstOffset} onChange={(firstOffset) => onChange({ firstOffset })} suffix="mm" /><Field label="Położenie B" value={command.secondOffset} onChange={(secondOffset) => onChange({ secondOffset })} suffix="mm" /></>}
            {isThreePointPlane && <>{[1, 2, 3].map((index) => <React.Fragment key={index}><Field label={`Punkt ${index} X`} value={command[`x${index}`]} onChange={(value) => onChange({ [`x${index}`]: value })} suffix="mm" /><Field label={`Punkt ${index} Y`} value={command[`y${index}`]} onChange={(value) => onChange({ [`y${index}`]: value })} suffix="mm" /><Field label={`Punkt ${index} Z`} value={command[`z${index}`]} onChange={(value) => onChange({ [`z${index}`]: value })} suffix="mm" /></React.Fragment>)}</>}
            {isAnglePlane && <><label className="command-field"><span>Oś obrotu</span><select value={command.rotationAxis} onChange={(event) => onChange({ rotationAxis: event.target.value })}><option value="u">Oś U</option><option value="v">Oś V</option></select></label><Field label="Kąt" value={command.angle} onChange={(angle) => onChange({ angle })} suffix="°" /><Field label="Odległość" value={command.offset} onChange={(offset) => onChange({ offset })} suffix="mm" /></>}
            {isTangentPlane && <><label className="command-field"><span>Powierzchnia</span><select value={command.surfaceType} onChange={(event) => onChange({ surfaceType: event.target.value })}><option value="sphere">Sfera</option><option value="cylinder">Walec</option></select></label>{['X', 'Y', 'Z'].map((axis, index) => <React.Fragment key={`tangent-${axis}`}><Field label={`Środek ${axis}`} value={command[`center${index}`]} onChange={(value) => onChange({ [`center${index}`]: value })} suffix="mm" /><Field label={`Styczność ${axis}`} value={command[`point${index}`]} onChange={(value) => onChange({ [`point${index}`]: value })} suffix="mm" />{command.surfaceType === 'cylinder' && <Field label={`Oś ${axis}`} value={command[`axis${index}`]} onChange={(value) => onChange({ [`axis${index}`]: value })} />}</React.Fragment>)}</>}
            {isPathPlane && <>{['X', 'Y', 'Z'].map((axis, index) => <React.Fragment key={`path-${axis}`}><Field label={`Punkt ścieżki ${axis}`} value={command[`point${index}`]} onChange={(value) => onChange({ [`point${index}`]: value })} suffix="mm" /><Field label={`Kierunek ścieżki ${axis}`} value={command[`direction${index}`]} onChange={(value) => onChange({ [`direction${index}`]: value })} /></React.Fragment>)}</>}
            <label className="command-field"><span>Widoczna</span><select value={command.visible ? 'yes' : 'no'} onChange={(event) => onChange({ visible: event.target.value === 'yes' })}><option value="yes">Tak</option><option value="no">Nie</option></select></label>
          </>
        )}
        {isConstructionAxis && (
          <>
            <Field label="Nazwa" value={command.name} onChange={(name) => onChange({ name })} autoFocus />
            {['edge', 'two-points'].includes(command.axisType) && <>{[1, 2].map((index) => <React.Fragment key={index}><Field label={`Punkt ${index} X`} value={command[`x${index}`]} onChange={(value) => onChange({ [`x${index}`]: value })} suffix="mm" /><Field label={`Punkt ${index} Y`} value={command[`y${index}`]} onChange={(value) => onChange({ [`y${index}`]: value })} suffix="mm" /><Field label={`Punkt ${index} Z`} value={command[`z${index}`]} onChange={(value) => onChange({ [`z${index}`]: value })} suffix="mm" /></React.Fragment>)}</>}
            {command.axisType === 'cylinder' && <>{['X', 'Y', 'Z'].map((axis, index) => <Field key={`origin-${axis}`} label={`Środek ${axis}`} value={command[`origin${index}`]} onChange={(value) => onChange({ [`origin${index}`]: value })} suffix="mm" />)}{['X', 'Y', 'Z'].map((axis, index) => <Field key={`direction-${axis}`} label={`Kierunek ${axis}`} value={command[`direction${index}`]} onChange={(value) => onChange({ [`direction${index}`]: value })} />)}</>}
            {command.axisType === 'plane-intersection' && <><label className="command-field"><span>Płaszczyzna A</span><select value={command.planeId1} onChange={(event) => onChange({ planeId1: event.target.value })}>{command.planeOptions.map((plane) => <option key={plane.id} value={plane.id}>{plane.name}</option>)}</select></label><label className="command-field"><span>Płaszczyzna B</span><select value={command.planeId2} onChange={(event) => onChange({ planeId2: event.target.value })}>{command.planeOptions.map((plane) => <option key={plane.id} value={plane.id}>{plane.name}</option>)}</select></label></>}
            {command.axisType === 'plane-normal' && <><label className="command-field"><span>Płaszczyzna</span><select value={command.planeId1} onChange={(event) => onChange({ planeId1: event.target.value })}>{command.planeOptions.map((plane) => <option key={plane.id} value={plane.id}>{plane.name}</option>)}</select></label>{['X', 'Y', 'Z'].map((axis, index) => <Field key={`normal-origin-${axis}`} label={`Punkt osi ${axis}`} value={command[`origin${index}`]} onChange={(value) => onChange({ [`origin${index}`]: value })} suffix="mm" />)}</>}
            <label className="command-field"><span>Widoczna</span><select value={command.visible ? 'yes' : 'no'} onChange={(event) => onChange({ visible: event.target.value === 'yes' })}><option value="yes">Tak</option><option value="no">Nie</option></select></label>
          </>
        )}
        {isConstructionPoint && (
          <>
            <Field label="Nazwa" value={command.name} onChange={(name) => onChange({ name })} autoFocus />
            {['vertex', 'center'].includes(command.pointType) && <>{['X', 'Y', 'Z'].map((axis, index) => <Field key={axis} label={axis} value={command[`position${index}`]} onChange={(value) => onChange({ [`position${index}`]: value })} suffix="mm" />)}</>}
            {command.pointType === 'intersection' && <><label className="command-field"><span>Oś</span><select value={command.axisId} onChange={(event) => onChange({ axisId: event.target.value })}>{command.axisOptions.map((axis) => <option key={axis.id} value={axis.id}>{axis.name}</option>)}</select></label><label className="command-field"><span>Płaszczyzna</span><select value={command.planeId} onChange={(event) => onChange({ planeId: event.target.value })}>{command.planeOptions.map((plane) => <option key={plane.id} value={plane.id}>{plane.name}</option>)}</select></label></>}
            {command.pointType === 'midpoint' && <>{[1, 2].map((index) => <React.Fragment key={index}>{['X', 'Y', 'Z'].map((axis) => <Field key={`${index}-${axis}`} label={`Punkt ${index} ${axis}`} value={command[`${axis.toLowerCase()}${index}`]} onChange={(value) => onChange({ [`${axis.toLowerCase()}${index}`]: value })} suffix="mm" />)}</React.Fragment>)}</>}
            {command.pointType === 'on-axis' && <><label className="command-field"><span>Oś</span><select value={command.axisId} onChange={(event) => onChange({ axisId: event.target.value })}>{command.axisOptions.map((axis) => <option key={axis.id} value={axis.id}>{axis.name}</option>)}</select></label><Field label="Odległość na osi" value={command.distance} onChange={(distance) => onChange({ distance })} suffix="mm" /></>}
            <label className="command-field"><span>Widoczny</span><select value={command.visible ? 'yes' : 'no'} onChange={(event) => onChange({ visible: event.target.value === 'yes' })}><option value="yes">Tak</option><option value="no">Nie</option></select></label>
          </>
        )}
        {isSketchPath && (
          <>
          {command.lastPoint && <label className="sketch-length-entry"><span>Długość następnego odcinka</span><div><input type="text" inputMode="decimal" value={command.dynamicLength || ''} placeholder="np. 25" onChange={(event) => { const value = event.target.value.replace(',', '.'); if (/^\d*(?:\.\d*)?$/.test(value)) onChange({ dynamicLength: value }); }} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); event.stopPropagation(); onConfirmDynamic?.(); } }} /><span>mm</span><kbd>Enter</kbd></div></label>}
          <details className="sketch-path-exact">
            <summary><span>Dokładna długość i kąt</span><small>opcjonalnie</small></summary>
            <div>
              <Field label="Długość" value={command.length} onChange={(length) => onChange({ length })} suffix="mm" />
              <Field label="Kąt" value={command.angle} onChange={(angle) => onChange({ angle })} suffix="°" />
              <label className="command-field">
                <span>Segment</span>
                <select value={command.segmentMode} onChange={(event) => onChange({ segmentMode: event.target.value })}>
                  <option value="line">Linia</option>
                  <option value="tangentArc" disabled={!command.segmentIds.length}>Łuk styczny</option>
                </select>
              </label>
            </div>
          </details>
          </>
        )}
        {isSketchMove && (
          <>
            <Field label="Przesunięcie X" value={command.dx} onChange={(dx) => onChange({ dx })} suffix="mm" autoFocus />
            <Field label="Przesunięcie Y" value={command.dy} onChange={(dy) => onChange({ dy })} suffix="mm" />
          </>
        )}
        {isSketchOffset && (
          <>
            <Field label="Odległość" value={command.distance} onChange={(distance) => onChange({ distance })} suffix="mm" autoFocus />
            <p className="command-hint">Wartość dodatnia przesuwa w lewo od kierunku krzywej, ujemna — na drugą stronę.</p>
          </>
        )}
        {isSketchCorner && <Field label={command.mode === 'fillet' ? 'Promień' : 'Odległość'} value={command.size} onChange={(size) => onChange({ size })} suffix="mm" autoFocus />}
        {isSketchTransform && (
          <>
            <label className="command-field"><span>Operacja</span><select value={command.operation} onChange={(event) => onChange({ operation: event.target.value })}><option value="rotate">Rotate</option><option value="copy">Copy</option><option value="mirror">Mirror</option><option value="scale">Scale</option></select></label>
            {command.operation === 'copy' ? <><Field label="Kopia ΔX" value={command.dx} onChange={(dx) => onChange({ dx })} suffix="mm" autoFocus /><Field label="Kopia ΔY" value={command.dy} onChange={(dy) => onChange({ dy })} suffix="mm" /></> : command.operation === 'mirror' ? <><label className="command-field"><span>Oś odbicia</span><select value={command.axis} onChange={(event) => onChange({ axis: event.target.value })}><option value="vertical">Pionowa X</option><option value="horizontal">Pozioma Y</option></select></label><Field label="Położenie osi" value={command.axisOffset} onChange={(axisOffset) => onChange({ axisOffset })} suffix="mm" autoFocus /></> : <><Field label="Środek X" value={command.centerX} onChange={(centerX) => onChange({ centerX })} suffix="mm" autoFocus /><Field label="Środek Y" value={command.centerY} onChange={(centerY) => onChange({ centerY })} suffix="mm" />{command.operation === 'rotate' ? <Field label="Kąt obrotu" value={command.angle} onChange={(angle) => onChange({ angle })} suffix="°" /> : <Field label="Skala" value={command.factor} onChange={(factor) => onChange({ factor })} />}</>}
          </>
        )}
        {isSketchPattern && (
          <>
            <label className="command-field"><span>Typ szyku</span><select value={command.mode} onChange={(event) => onChange({ mode: event.target.value })}><option value="rectangular">Prostokątny</option><option value="circular">Kołowy</option><option value="path">Po ścieżce</option></select></label>
            {command.mode === 'rectangular' ? <><Field label="Kolumny" value={command.columns} onChange={(columns) => onChange({ columns })} autoFocus /><Field label="Wiersze" value={command.rows} onChange={(rows) => onChange({ rows })} /><Field label="Odstęp X" value={command.spacingX} onChange={(spacingX) => onChange({ spacingX })} suffix="mm" /><Field label="Odstęp Y" value={command.spacingY} onChange={(spacingY) => onChange({ spacingY })} suffix="mm" /></> : command.mode === 'circular' ? <><Field label="Wystąpienia" value={command.count} onChange={(count) => onChange({ count })} autoFocus /><Field label="Środek X" value={command.centerX} onChange={(centerX) => onChange({ centerX })} suffix="mm" /><Field label="Środek Y" value={command.centerY} onChange={(centerY) => onChange({ centerY })} suffix="mm" /><Field label="Kąt całkowity" value={command.totalAngle} onChange={(totalAngle) => onChange({ totalAngle })} suffix="°" /></> : <><label className="command-field"><span>Ścieżka</span><select value={command.pathEntityId} onChange={(event) => onChange({ pathEntityId: event.target.value })}>{command.pathOptions.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><Field label="Wystąpienia" value={command.count} onChange={(count) => onChange({ count })} autoFocus /><label className="command-field"><span>Orientacja</span><select value={command.orientToPath ? 'path' : 'fixed'} onChange={(event) => onChange({ orientToPath: event.target.value === 'path' })}><option value="path">Zgodnie ze ścieżką</option><option value="fixed">Stała</option></select></label></>}
            <Field label="Pomiń wystąpienia" value={command.skippedOccurrences} onChange={(skippedOccurrences) => onChange({ skippedOccurrences })} />
            <p className="command-hint">Numery oddziel przecinkami lub podaj zakres, np. 3, 5-7. Wystąpienie 1 jest źródłem.</p>
          </>
        )}
        {!isSketchPath && <div className="command-preview-note"><span className="preview-dot" />{isSketchMove ? 'Wpisz dokładne przesunięcie zaznaczenia w osiach szkicu.' : isSketchOffset ? 'Operacja powstanie dopiero po zatwierdzeniu; Anuluj nie zmienia szkicu.' : isSketchCorner ? 'Oryginalne linie zachowają ID; zerwane więzy zostaną jawnie usunięte.' : isSketchTransform ? 'Transformacja jest transakcyjna; Scale odrzuca geometrię z blokującym wymiarem.' : isSketchPattern ? 'Szyk powstanie transakcyjnie; pominięte kopie nie zostaną utworzone.' : isConstructionPlane ? 'Współrzędne i odległości mogą być liczbami albo wyrażeniami z parametrów modelu.' : isPoint ? 'Kliknij położenie na płótnie. Pola X/Y są opcjonalnym wejściem dokładnym.' : isMechanicalShape ? 'Klikaj punkty figury na płótnie. Pola pozostają opcjonalnym wejściem dokładnym.' : isExtrude ? 'Przeciągnij niebieską strzałkę na modelu albo wpisz dokładną odległość.' : 'Podgląd jest przeliczany na dokładnej bryle B-Rep.'}</div>}
      </div>
      {isSketchPath ? (
        <footer><button className="secondary" type="button" onClick={onUndoSegment} disabled={!command.pointIds.length}>Cofnij segment</button><button className="secondary" type="button" onClick={onFinishPath}>Zakończ</button><button className="confirm" type="button" onClick={onConfirm} disabled={!command.lastPoint}><Check size={14} /> Dodaj dokładnie</button></footer>
      ) : (
        <footer><button className="secondary" type="button" onClick={onCancel}>Anuluj</button><button className="confirm" type="button" onClick={onConfirm} disabled={featurePreviewPending} aria-busy={featurePreviewPending} title={featurePreviewPending ? 'Trwa obliczanie podglądu operacji' : undefined}><Check size={14} /> {featurePreviewPending ? 'Obliczanie…' : isMechanicalShape || isPoint ? 'Utwórz z danych' : 'OK'}</button></footer>
      )}
      </>}
    </section>
  );
}
